# Generated by Django 3.0.5 on 2021-02-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=200, null=True)),
                ('contact', models.CharField(max_length=50000000000)),
                ('dob', models.DateField()),
                ('blood', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('O+', 'O-'), ('AB+', 'AB-')], max_length=200, null=True)),
                ('district', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('Ward_no', models.IntegerField()),
            ],
        ),
    ]
