# Generated by Django 3.0.5 on 2021-02-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackfest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='city_town',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='Ward_no',
            new_name='ward',
        ),
    ]
