# Generated by Django 3.0.5 on 2021-02-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackfest', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
