# Generated by Django 3.0.5 on 2021-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackfest', '0002_auto_20210219_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='ward',
            field=models.IntegerField(null=True),
        ),
    ]
