# Generated by Django 3.0.5 on 2021-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackfest', '0003_auto_20210219_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=50000000, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('website', models.CharField(max_length=50000)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
