# Generated by Django 3.0.5 on 2021-02-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackfest', '0004_bloodbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB-')], max_length=200, null=True),
        ),
    ]
