# Generated by Django 3.1.7 on 2021-02-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackfest', '0005_auto_20210220_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='website',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
